services:
  - type: web
    name: my-portfolio
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: your_secret_key_here
